# Generated by Django 2.1.7 on 2019-06-10 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=54, verbose_name='location')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=35, verbose_name='email')),
                ('age', models.IntegerField(default=18)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='employement_date')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Employee')),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Employee'),
        ),
    ]
